// 명령 팔레트 날짜·시각 넣기 (specs/features/F-2088.md)
import { test, expect } from '@playwright/test'
import { openApp, importMarkdown, readSavedContent, setViewMode } from './helpers.js'

const FIXED_NOW = new Date(2026, 8, 23, 9, 5, 7)
const palette = (page) => page.locator('dialog[open] .command-palette')
const focusedInContent = (page) => page.evaluate(() => document.activeElement?.closest('.cm-content') != null)

test.describe('F-2088 팔레트 날짜·시각 넣기', () => {
  test('F-2088 A1 본문에서 — 선택을 바꾸고 되돌리기 한 번', async ({ page }) => {
    await page.clock.setFixedTime(FIXED_NOW)
    await openApp(page)
    const docId = await importMarkdown(page, { content: '가나다 라마\n' })
    await page.locator('.cm-line', { hasText: '가나다 라마' }).click()
    await page.keyboard.press('End')
    await page.keyboard.press('Shift+ArrowLeft')
    await page.keyboard.press('Shift+ArrowLeft')
    await page.keyboard.press('Control+p')
    await page.keyboard.type('>날짜')
    await expect(palette(page).getByRole('option').first()).toHaveText(/오늘 날짜 넣기/)
    await page.keyboard.press('Enter')
    await expect(palette(page)).toHaveCount(0)
    await expect.poll(async () => (await readSavedContent(page, docId)).content).toBe('가나다 2026-09-23\n')
    await expect.poll(() => focusedInContent(page)).toBe(true)
    await page.keyboard.press('Control+z')
    await expect.poll(async () => (await readSavedContent(page, docId)).content).toBe('가나다 라마\n')
  })

  test('F-2088 A2 제목 입력에서 연 팔레트 — 마지막 커서 자리, 포커스는 본문', async ({ page }) => {
    await page.clock.setFixedTime(FIXED_NOW)
    await openApp(page)
    const docId = await importMarkdown(page, { content: '첫 줄\n' })
    await setViewMode(page, 'raw')
    await page.locator('.cm-line', { hasText: '첫 줄' }).click()
    await page.keyboard.press('End')
    const title = page.locator('.doc-title')
    const titleBefore = await title.inputValue()
    await title.click()
    await page.keyboard.press('Control+p')
    await page.keyboard.type('>시각')
    await page.keyboard.press('Enter')
    await expect(palette(page)).toHaveCount(0)
    await expect.poll(async () => (await readSavedContent(page, docId)).content).toBe('첫 줄09:05\n')
    await expect.poll(() => focusedInContent(page)).toBe(true)
    await page.keyboard.type('X')
    await expect.poll(async () => (await readSavedContent(page, docId)).content).toBe('첫 줄09:05X\n')
    expect(await title.inputValue()).toBe(titleBefore)
  })

  test('F-2088 A3 표 칸에서 열면 없다', async ({ page }) => {
    await page.clock.setFixedTime(FIXED_NOW)
    await openApp(page)
    const src = '표\n\n| a | b |\n| --- | --- |\n| 1 | 2 |\n'
    const docId = await importMarkdown(page, { content: src })
    await page.locator('.md-table-widget th').first().click()
    const cellLine = page.locator('.md-table-cell-editing .cm-line').first()
    const box = await cellLine.boundingBox()
    await page.mouse.click(box.x + 2, box.y + box.height / 2, { button: 'right' })
    await page.locator('.context-menu-root [role="menuitem"]').last().click()
    await expect(palette(page)).toBeVisible()
    await page.keyboard.type('>날짜')
    await expect(palette(page).getByRole('option')).toHaveCount(0)
    await expect(palette(page)).toContainText('맞는 명령이 없습니다')
    await page.keyboard.press('Escape')
    await expect(palette(page)).toHaveCount(0)
    await expect.poll(async () => (await readSavedContent(page, docId)).content).toBe(src)
  })
})
